### ISSUE TITLE
How to do the Input?

### ISSUE THREAD

**Issue by QLaHPD** [divelab/Noise2Same#1]
I've made this code to create the input pipeline:

```
import os
import argparse
import random
import numpy as np
import skimage.io as io
import skimage.color as color

from models import Noise2Same

parser = argparse.ArgumentParser()
parser.add_argument('--dataset_path', type=str, required=True)
parser.add_argument('--output_path', type=str, required=True)
parser.add_argument('--image_size', type=int, default=64)
parser.add_argument('--cache_samples', type=int, default=1024)
opt = parser.parse_args()


def load_dataset(path, samples=1024, image_size=32):
	batch_noise_images = np.empty((samples, image_size, image_size, 3), dtype=np.float32)
	imgs = os.listdir(path)

	for img in range(samples):
		image = io.imread(os.path.join(path, imgs[img]))
		image = color.gray2rgb(image)
		crop_x, crop_y = random.randint(0, image.shape[1] - image_size), random.randint(0, image.shape[0] - image_size)

		image = image[crop_y:crop_y+image_size, crop_x:crop_x + image_size]
		batch_noise_images[img] = image / 255.0

		return batch_noise_images


model = Noise2Same(opt.output_path, 'model', 2, 3)

train_images = load_dataset(opt.dataset_path, samples=opt.cache_samples, image_size=opt.image_size)

model.train(train_images, int(opt.image_size/2), validation=None, batch_size=32, steps=1e6)
```
So I'm passing the images in format [n_samples, width, length, n_channels], but it does not work, return erros like:
```
line 181, in train
    assert len(patch_size)==self.dim
TypeError: object of type 'int' has no len()
```
So, how the code expects the input?

**Comment by QLaHPD** [comment]
I've fixed the first error that was pretty simple (pass the patch_size in shape [x, y]).
But now it gives a new error:

```
python train.py --dataset_path /mnt/ramdisk/train/ --output_path /mnt/ramdisk/output/ --cache_samples 1024 --image_size 128
train.py:24: FutureWarning: Pass-through of possibly RGB images in gray2rgb is deprecated. In version 0.19, input arrays will always be considered grayscale, even if the last dimension has length 3 or 4. To prevent this warning and ensure compatibility with future versions, detect RGB images outside of this function.
  image = color.gray2rgb(image)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 594, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/user/anaconda3/envs/NOISE2SAME/Noise2Same-main/models.py", line 144, in generator
    source_patch = augment_patch(source[s])

TypeError: slice indices must be integers or None or have an __index__ method


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 594, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/user/anaconda3/envs/NOISE2SAME/Noise2Same-main/models.py", line 144, in generator
    source_patch = augment_patch(source[s])

TypeError: slice indices must be integers or None or have an __index__ method


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_1273]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 37, in <module>
    model.train(train_images, [opt.image_size/2, opt.image_size/2] , validation=None, batch_size=32, steps=1e6)
  File "/home/user/anaconda3/envs/NOISE2SAME/Noise2Same-main/models.py", line 210, in train
    estimator.train(input_fn=input_fn, steps=steps)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 594, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/user/anaconda3/envs/NOISE2SAME/Noise2Same-main/models.py", line 144, in generator
    source_patch = augment_patch(source[s])

TypeError: slice indices must be integers or None or have an __index__ method


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
  (1) Invalid argument: TypeError: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/NOISE2SAME/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 594, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/user/anaconda3/envs/NOISE2SAME/Noise2Same-main/models.py", line 144, in generator
    source_patch = augment_patch(source[s])

TypeError: slice indices must be integers or None or have an __index__ method


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_1273]]
0 successful operations.
0 derived errors ignored.
```
I'm using tensorflow-gpu 1.15.

**Comment by QLaHPD** [comment]
I've fixed it by loading the whole image, not sure what caused the previous error.
