### ISSUE TITLE
what i missing here?

### ISSUE THREAD

**Issue by johnfelipe** [divelab/Noise2Same#4]
root@uno-ubuntu-s-8vcpu-16gb-nyc1-01:~/Noise2Same# python3 demo.py              Traceback (most recent call last):
      File "demo.py", line 2, in <module>
        from models import Noise2Same
      File "/root/Noise2Same/models.py", line 3, in <module>
        from network_configure import conf_unet
      File "/root/Noise2Same/network_configure.py", line 20, in <module>
        conf_basic_ops['kernel_initializer'] = tf.glorot_uniform_initializer()
    AttributeError: module 'tensorflow' has no attribute 'glorot_uniform_initializer'

**Comment by johnfelipe** [comment]
can u tell me how can deploy correctly this gradio instance?

**Comment by johnfelipe** [comment]
i change tensorflow to 1.16 but now show me this

    Traceback (most recent call last):
      File "demo.py", line 2, in <module>
        from models import Noise2Same
      File "/root/Noise2Same/models.py", line 1, in <module>
        import os, cv2
      File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 5, in <module>
        from .cv2 import *
    ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by ycremar** [comment]
Hi @johnfelipe, sorry for the late reply. It seems to be a issue of cv2 compatibility. Could you try if this solution works?
https://stackoverflow.com/questions/63977422/error-trying-to-import-cv2opencv-python-package
